services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siga_first_bot
    restart: unless-stopped
    ports:
      - "3008:3008"
    volumes:
      - ./backend/data:/app/data
      - ./backend/backups:/app/backups
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
