services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH}
    container_name: steam_bot
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${PORT}"
    environment:
      - PORT=${PORT}
    volumes:
      - ./backend/data:/app/data
      - ./backend/backups:/app/backups
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
